import Foundation
import SwiftData

/// Persistent analysis report generated by an LLM for a JournalEntry.
@Model
public final class AnalysisReport {
    public var id: UUID = UUID()
    public var createdAt: Date = Date()
    public var providerName: String = "DeepSeek"
    public var modelUsed: String = "deepseek-chat"
    public var evaluatedLevel: String = "HSK 1"
    
    public var overallScore: Int = 85 // 0-100 scale
    public var fluencySummary: String = ""
    public var encouragingFeedback: String = ""
    
    // JSON-encoded arrays for SwiftData compatibility
    public var correctionsData: Data = Data()
    public var vocabularyData: Data = Data()
    public var grammarPatternsData: Data = Data()
    
    public var polishedVersion: String = ""
    public var rawResponse: String = ""
    
    public var journalEntry: JournalEntry?
    
    public init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        providerName: String = "DeepSeek",
        modelUsed: String = "deepseek-chat",
        evaluatedLevel: String = "HSK 1",
        overallScore: Int = 85,
        fluencySummary: String = "",
        encouragingFeedback: String = "",
        corrections: [GrammarCorrection] = [],
        vocabularyRecommendations: [VocabularyItem] = [],
        grammarPatterns: [GrammarPatternHighlight] = [],
        polishedVersion: String = "",
        rawResponse: String = ""
    ) {
        self.id = id
        self.createdAt = createdAt
        self.providerName = providerName
        self.modelUsed = modelUsed
        self.evaluatedLevel = evaluatedLevel
        self.overallScore = overallScore
        self.fluencySummary = fluencySummary
        self.encouragingFeedback = encouragingFeedback
        self.polishedVersion = polishedVersion
        self.rawResponse = rawResponse
        
        self.setCorrections(corrections)
        self.setVocabulary(vocabularyRecommendations)
        self.setGrammarPatterns(grammarPatterns)
    }
    
    // Decoded accessors
    public var corrections: [GrammarCorrection] {
        get {
            let decoded = (try? JSONDecoder().decode([GrammarCorrection].self, from: correctionsData)) ?? []
            return decoded.filter { $0.isValidCorrection }
        }
        set {
            let valid = newValue.filter { $0.isValidCorrection }
            correctionsData = (try? JSONEncoder().encode(valid)) ?? Data()
        }
    }
    
    public var vocabularyRecommendations: [VocabularyItem] {
        get {
            (try? JSONDecoder().decode([VocabularyItem].self, from: vocabularyData)) ?? []
        }
        set {
            vocabularyData = (try? JSONEncoder().encode(newValue)) ?? Data()
        }
    }
    
    public var grammarPatterns: [GrammarPatternHighlight] {
        get {
            (try? JSONDecoder().decode([GrammarPatternHighlight].self, from: grammarPatternsData)) ?? []
        }
        set {
            grammarPatternsData = (try? JSONEncoder().encode(newValue)) ?? Data()
        }
    }
    
    public func setCorrections(_ items: [GrammarCorrection]) {
        let valid = items.filter { $0.isValidCorrection }
        self.correctionsData = (try? JSONEncoder().encode(valid)) ?? Data()
    }
    
    public func setVocabulary(_ items: [VocabularyItem]) {
        self.vocabularyData = (try? JSONEncoder().encode(items)) ?? Data()
    }
    
    public func setGrammarPatterns(_ items: [GrammarPatternHighlight]) {
        self.grammarPatternsData = (try? JSONEncoder().encode(items)) ?? Data()
    }
}
